// Code generated by protoc-gen-go-grpc. DO NOT EDIT.

package v1

import (
	grpc "google.golang.org/grpc"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// UserErrorClient is the client API for UserError service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type UserErrorClient interface {
}

type userErrorClient struct {
	cc grpc.ClientConnInterface
}

func NewUserErrorClient(cc grpc.ClientConnInterface) UserErrorClient {
	return &userErrorClient{cc}
}

// UserErrorServer is the server API for UserError service.
// All implementations must embed UnimplementedUserErrorServer
// for forward compatibility
type UserErrorServer interface {
	mustEmbedUnimplementedUserErrorServer()
}

// UnimplementedUserErrorServer must be embedded to have forward compatible implementations.
type UnimplementedUserErrorServer struct {
}

func (UnimplementedUserErrorServer) mustEmbedUnimplementedUserErrorServer() {}

// UnsafeUserErrorServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to UserErrorServer will
// result in compilation errors.
type UnsafeUserErrorServer interface {
	mustEmbedUnimplementedUserErrorServer()
}

func RegisterUserErrorServer(s grpc.ServiceRegistrar, srv UserErrorServer) {
	s.RegisterService(&UserError_ServiceDesc, srv)
}

// UserError_ServiceDesc is the grpc.ServiceDesc for UserError service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var UserError_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "api.edge.user.interface.v1.User_error",
	HandlerType: (*UserErrorServer)(nil),
	Methods:     []grpc.MethodDesc{},
	Streams:     []grpc.StreamDesc{},
	Metadata:    "api/edge/user/interface/v1/user_error.proto",
}
