// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"github.com/go-kratos/kratos/v2"
	"github.com/go-kratos/kratos/v2/log"
	"microservice/app/edge/user/interface/internal/biz"
	"microservice/app/edge/user/interface/internal/conf"
	"microservice/app/edge/user/interface/internal/data"
	"microservice/app/edge/user/interface/internal/server"
	"microservice/app/edge/user/interface/internal/service"
)

// Injectors from wire.go:

// initApp init kratos application.
func initApp(confServer *conf.Server, confData *conf.Data, logger log.Logger) (*kratos.App, func(), error) {
	client := data.NewRedisClient(confData)
	emailClient := data.NewEmailServiceClient()
	mobileClient := data.NewMobileServiceClient()
	userClient := data.NewUserServiceClient()
	dataData, cleanup, err := data.NewData(logger, client, emailClient, mobileClient, userClient)
	if err != nil {
		return nil, nil, err
	}
	userRepo := data.NewUserRepo(dataData, logger)
	userUseCase := biz.NewUserUseCase(userRepo, logger)
	userInterface := service.NewUserEdgeInterfaceService(userUseCase, logger)
	httpServer := server.NewHTTPServer(confServer, logger, userInterface)
	app := newApp(logger, httpServer)
	return app, func() {
		cleanup()
	}, nil
}
