FROM golang:1.17 AS builder

COPY . /src
WORKDIR /src

RUN GOPROXY=https://goproxy.cn make build-edgeCourse

FROM centos:7

COPY --from=builder /src/edgeCourse/bin /app

WORKDIR /app

EXPOSE 8001
VOLUME /data/conf

CMD ["./server", "-conf", "/data/conf"]
