FROM golang:1.17 AS builder

COPY . /src
WORKDIR /src

RUN GOPROXY=https://goproxy.cn make build-user

FROM centos:7

COPY --from=builder /src/user/bin /app

WORKDIR /app

EXPOSE 10901
VOLUME /data/conf

CMD ["./server", "-conf", "/data/conf"]
