FROM golang:1.17 AS builder

COPY . /src
WORKDIR /src

RUN GOPROXY=https://goproxy.cn make build-message

FROM centos:7

COPY --from=builder /src/message/bin /app

WORKDIR /app

EXPOSE 10900
VOLUME /data/conf

CMD ["./server", "-conf", "/data/conf"]
