FROM golang:1.17 AS builder

COPY . /src
WORKDIR /src

RUN GOPROXY=https://goproxy.cn make build-course

FROM centos:7

COPY --from=builder /src/course/bin /app

WORKDIR /app

EXPOSE 10903
VOLUME /data/conf

CMD ["./server", "-conf", "/data/conf"]
