FROM golang:1.17 AS builder

COPY . /src
WORKDIR /src

RUN GOPROXY=https://goproxy.cn make build-apigateway

FROM centos:7

COPY --from=builder /src/apigateway/bin /app

WORKDIR /app

EXPOSE 80
VOLUME /data/conf

CMD ["./server"]
