FROM golang:1.17 AS builder

COPY . /src
WORKDIR /src

RUN GOPROXY=https://goproxy.cn make build-edgeUser

FROM centos:7

COPY --from=builder /src/edgeUser/bin /app

WORKDIR /app

EXPOSE 8000
VOLUME /data/conf

CMD ["./server", "-conf", "/data/conf"]
