trace:
  endpoint: http://172.16.20.198:30050/api/traces
server:
  grpc:
    addr: 0.0.0.0:10901
    timeout: 1s
data:
  database:
    driver: mysql
    source: root:123456@tcp(${MYSQL_ADDR}:${MYSQL_PORT})/userdb?parseTime=true


