apiVersion: v1
kind: Service
metadata:
  name: user-service
  labels:
    app: user
spec:
  type: ClusterIP
  selector:
    matchLabels:
      app: user
  ports:
  - name: user
    port: 10901
    targetPort: 10901
  - name: user-edge
    port: 8000
    targetPort: 8000
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: user-config
data:
  config.yaml: |
    server.grpc.addr=0.0.0.0:10901
    server.grpc.timeout=1s
    data.database.driver=mysql
    data.database.source=root:123456@tcp(${MYSQL_ADDR}:${MYSQL_PORT})/userdb?parseTime=true
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: user-edge-config
data:
  config.yaml: |
    server.http.addr=0.0.0.0:8000
    server.http.timeout=5s
    data.redis.addr=${REDIS_ADDR}
    data.redis.password=""
    data.redis.dial_timeout=1s
    data.redis.read_timeout=0.4s
    data.redis.write_timeout=0.6s
    external.message_service.addr=message-service
    external.message_service.port=10900
    external.user_service.addr=localhost
    external.user_service.port=10901
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: user-service
  labels:
    app: user

spec:
  replicas: 2
  selector:
    matchLabels:
      app: user
  template:
    metadata:
      labels:
        app: user
    spec:
      containers:
        - name: user
          image: 193.168.1.211:8082/microservice/user:1
          env:
            - name: "MYSQL_ADDR"
              value: "172.16.20.198"
            - name: "MYSQL_PORT"
              value: "30600"
          ports:
            - name: user
              containerPort: 10901
          volumeMounts:
            - name: user-config
              mountPath: "/data/conf"
              readOnly: true
        - name: user-edge
          image: 193.168.1.211:8082/microservice/user-edge:1
          env:
            - name: "REDIS_ADDR"
              value: "172.16.20.198:31971"
          ports:
            - name: user-edge
              containerPort: 8000
          volumeMounts:
            - name: user-edge-config
              mountPath: "/data/conf"
              readOnly: true
      volumes:
        - name: user-config
          configMap:
            name: user-config
            items:
              - key: "config.yaml"
                path: "config.yaml"
        - name: user-edge-config
          configMap:
            name: user-edge-config
            items:
              - key: "config.yaml"
                path: "config.yaml"