// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.27.1
// 	protoc        v3.14.0
// source: api/course/service/v1/course.proto

package v1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ListCourseRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *ListCourseRequest) Reset() {
	*x = ListCourseRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_course_service_v1_course_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ListCourseRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListCourseRequest) ProtoMessage() {}

func (x *ListCourseRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_course_service_v1_course_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListCourseRequest.ProtoReflect.Descriptor instead.
func (*ListCourseRequest) Descriptor() ([]byte, []int) {
	return file_api_course_service_v1_course_proto_rawDescGZIP(), []int{0}
}

type ListCourseReply struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Courses []*ListCourseReply_Course `protobuf:"bytes,1,rep,name=courses,proto3" json:"courses,omitempty"`
}

func (x *ListCourseReply) Reset() {
	*x = ListCourseReply{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_course_service_v1_course_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ListCourseReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListCourseReply) ProtoMessage() {}

func (x *ListCourseReply) ProtoReflect() protoreflect.Message {
	mi := &file_api_course_service_v1_course_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListCourseReply.ProtoReflect.Descriptor instead.
func (*ListCourseReply) Descriptor() ([]byte, []int) {
	return file_api_course_service_v1_course_proto_rawDescGZIP(), []int{1}
}

func (x *ListCourseReply) GetCourses() []*ListCourseReply_Course {
	if x != nil {
		return x.Courses
	}
	return nil
}

type ListCourseReply_Course struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ID          int64  `protobuf:"varint,1,opt,name=ID,proto3" json:"ID,omitempty"`
	Title       string `protobuf:"bytes,2,opt,name=title,proto3" json:"title,omitempty"`
	Description string `protobuf:"bytes,3,opt,name=description,proto3" json:"description,omitempty"`
	TeacherId   int64  `protobuf:"varint,4,opt,name=teacher_id,json=teacherId,proto3" json:"teacher_id,omitempty"`
}

func (x *ListCourseReply_Course) Reset() {
	*x = ListCourseReply_Course{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_course_service_v1_course_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ListCourseReply_Course) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListCourseReply_Course) ProtoMessage() {}

func (x *ListCourseReply_Course) ProtoReflect() protoreflect.Message {
	mi := &file_api_course_service_v1_course_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListCourseReply_Course.ProtoReflect.Descriptor instead.
func (*ListCourseReply_Course) Descriptor() ([]byte, []int) {
	return file_api_course_service_v1_course_proto_rawDescGZIP(), []int{1, 0}
}

func (x *ListCourseReply_Course) GetID() int64 {
	if x != nil {
		return x.ID
	}
	return 0
}

func (x *ListCourseReply_Course) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *ListCourseReply_Course) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *ListCourseReply_Course) GetTeacherId() int64 {
	if x != nil {
		return x.TeacherId
	}
	return 0
}

var File_api_course_service_v1_course_proto protoreflect.FileDescriptor

var file_api_course_service_v1_course_proto_rawDesc = []byte{
	0x0a, 0x22, 0x61, 0x70, 0x69, 0x2f, 0x63, 0x6f, 0x75, 0x72, 0x73, 0x65, 0x2f, 0x73, 0x65, 0x72,
	0x76, 0x69, 0x63, 0x65, 0x2f, 0x76, 0x31, 0x2f, 0x63, 0x6f, 0x75, 0x72, 0x73, 0x65, 0x2e, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x12, 0x15, 0x61, 0x70, 0x69, 0x2e, 0x63, 0x6f, 0x75, 0x72, 0x73, 0x65,
	0x2e, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x2e, 0x76, 0x31, 0x22, 0x13, 0x0a, 0x11, 0x4c,
	0x69, 0x73, 0x74, 0x43, 0x6f, 0x75, 0x72, 0x73, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74,
	0x22, 0xcb, 0x01, 0x0a, 0x0f, 0x4c, 0x69, 0x73, 0x74, 0x43, 0x6f, 0x75, 0x72, 0x73, 0x65, 0x52,
	0x65, 0x70, 0x6c, 0x79, 0x12, 0x47, 0x0a, 0x07, 0x63, 0x6f, 0x75, 0x72, 0x73, 0x65, 0x73, 0x18,
	0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x2d, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x63, 0x6f, 0x75, 0x72,
	0x73, 0x65, 0x2e, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x2e, 0x76, 0x31, 0x2e, 0x4c, 0x69,
	0x73, 0x74, 0x43, 0x6f, 0x75, 0x72, 0x73, 0x65, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x2e, 0x43, 0x6f,
	0x75, 0x72, 0x73, 0x65, 0x52, 0x07, 0x63, 0x6f, 0x75, 0x72, 0x73, 0x65, 0x73, 0x1a, 0x6f, 0x0a,
	0x06, 0x43, 0x6f, 0x75, 0x72, 0x73, 0x65, 0x12, 0x0e, 0x0a, 0x02, 0x49, 0x44, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x03, 0x52, 0x02, 0x49, 0x44, 0x12, 0x14, 0x0a, 0x05, 0x74, 0x69, 0x74, 0x6c, 0x65,
	0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x74, 0x69, 0x74, 0x6c, 0x65, 0x12, 0x20, 0x0a,
	0x0b, 0x64, 0x65, 0x73, 0x63, 0x72, 0x69, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x18, 0x03, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x0b, 0x64, 0x65, 0x73, 0x63, 0x72, 0x69, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x12,
	0x1d, 0x0a, 0x0a, 0x74, 0x65, 0x61, 0x63, 0x68, 0x65, 0x72, 0x5f, 0x69, 0x64, 0x18, 0x04, 0x20,
	0x01, 0x28, 0x03, 0x52, 0x09, 0x74, 0x65, 0x61, 0x63, 0x68, 0x65, 0x72, 0x49, 0x64, 0x32, 0x68,
	0x0a, 0x06, 0x43, 0x6f, 0x75, 0x72, 0x73, 0x65, 0x12, 0x5e, 0x0a, 0x0a, 0x4c, 0x69, 0x73, 0x74,
	0x43, 0x6f, 0x75, 0x72, 0x73, 0x65, 0x12, 0x28, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x63, 0x6f, 0x75,
	0x72, 0x73, 0x65, 0x2e, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x2e, 0x76, 0x31, 0x2e, 0x4c,
	0x69, 0x73, 0x74, 0x43, 0x6f, 0x75, 0x72, 0x73, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74,
	0x1a, 0x26, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x63, 0x6f, 0x75, 0x72, 0x73, 0x65, 0x2e, 0x73, 0x65,
	0x72, 0x76, 0x69, 0x63, 0x65, 0x2e, 0x76, 0x31, 0x2e, 0x4c, 0x69, 0x73, 0x74, 0x43, 0x6f, 0x75,
	0x72, 0x73, 0x65, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x42, 0x40, 0x0a, 0x15, 0x61, 0x70, 0x69, 0x2e,
	0x63, 0x6f, 0x75, 0x72, 0x73, 0x65, 0x2e, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x2e, 0x76,
	0x31, 0x50, 0x01, 0x5a, 0x25, 0x6d, 0x69, 0x63, 0x72, 0x6f, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63,
	0x65, 0x2f, 0x61, 0x70, 0x69, 0x2f, 0x63, 0x6f, 0x75, 0x72, 0x73, 0x65, 0x2f, 0x73, 0x65, 0x72,
	0x76, 0x69, 0x63, 0x65, 0x2f, 0x76, 0x31, 0x3b, 0x76, 0x31, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x33,
}

var (
	file_api_course_service_v1_course_proto_rawDescOnce sync.Once
	file_api_course_service_v1_course_proto_rawDescData = file_api_course_service_v1_course_proto_rawDesc
)

func file_api_course_service_v1_course_proto_rawDescGZIP() []byte {
	file_api_course_service_v1_course_proto_rawDescOnce.Do(func() {
		file_api_course_service_v1_course_proto_rawDescData = protoimpl.X.CompressGZIP(file_api_course_service_v1_course_proto_rawDescData)
	})
	return file_api_course_service_v1_course_proto_rawDescData
}

var file_api_course_service_v1_course_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_api_course_service_v1_course_proto_goTypes = []interface{}{
	(*ListCourseRequest)(nil),      // 0: api.course.service.v1.ListCourseRequest
	(*ListCourseReply)(nil),        // 1: api.course.service.v1.ListCourseReply
	(*ListCourseReply_Course)(nil), // 2: api.course.service.v1.ListCourseReply.Course
}
var file_api_course_service_v1_course_proto_depIdxs = []int32{
	2, // 0: api.course.service.v1.ListCourseReply.courses:type_name -> api.course.service.v1.ListCourseReply.Course
	0, // 1: api.course.service.v1.Course.ListCourse:input_type -> api.course.service.v1.ListCourseRequest
	1, // 2: api.course.service.v1.Course.ListCourse:output_type -> api.course.service.v1.ListCourseReply
	2, // [2:3] is the sub-list for method output_type
	1, // [1:2] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_api_course_service_v1_course_proto_init() }
func file_api_course_service_v1_course_proto_init() {
	if File_api_course_service_v1_course_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_api_course_service_v1_course_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ListCourseRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_course_service_v1_course_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ListCourseReply); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_course_service_v1_course_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ListCourseReply_Course); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_api_course_service_v1_course_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_api_course_service_v1_course_proto_goTypes,
		DependencyIndexes: file_api_course_service_v1_course_proto_depIdxs,
		MessageInfos:      file_api_course_service_v1_course_proto_msgTypes,
	}.Build()
	File_api_course_service_v1_course_proto = out.File
	file_api_course_service_v1_course_proto_rawDesc = nil
	file_api_course_service_v1_course_proto_goTypes = nil
	file_api_course_service_v1_course_proto_depIdxs = nil
}
