// Code generated by protoc-gen-go-http. DO NOT EDIT.
// versions:
// protoc-gen-go-http v2.0.5

package v1

import (
	context "context"
	http "github.com/go-kratos/kratos/v2/transport/http"
	binding "github.com/go-kratos/kratos/v2/transport/http/binding"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the kratos package it is being compiled against.
var _ = new(context.Context)
var _ = binding.EncodeURL

const _ = http.SupportPackageIsVersion1

type CourseEdgeInterfaceHTTPServer interface {
	ListCourse(context.Context, *ListCourseRequest) (*ListCourseReply, error)
}

func RegisterCourseEdgeInterfaceHTTPServer(s *http.Server, srv CourseEdgeInterfaceHTTPServer) {
	r := s.Route("/")
	r.GET("/v1/course", _CourseEdgeInterface_ListCourse0_HTTP_Handler(srv))
}

func _CourseEdgeInterface_ListCourse0_HTTP_Handler(srv CourseEdgeInterfaceHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in ListCourseRequest
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, "/api.edge.course.interface.v1.CourseEdgeInterface/ListCourse")
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.ListCourse(ctx, req.(*ListCourseRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*ListCourseReply)
		return ctx.Result(200, reply)
	}
}

type CourseEdgeInterfaceHTTPClient interface {
	ListCourse(ctx context.Context, req *ListCourseRequest, opts ...http.CallOption) (rsp *ListCourseReply, err error)
}

type CourseEdgeInterfaceHTTPClientImpl struct {
	cc *http.Client
}

func NewCourseEdgeInterfaceHTTPClient(client *http.Client) CourseEdgeInterfaceHTTPClient {
	return &CourseEdgeInterfaceHTTPClientImpl{client}
}

func (c *CourseEdgeInterfaceHTTPClientImpl) ListCourse(ctx context.Context, in *ListCourseRequest, opts ...http.CallOption) (*ListCourseReply, error) {
	var out ListCourseReply
	pattern := "/v1/course"
	path := binding.EncodeURL(pattern, in, true)
	opts = append(opts, http.Operation("/api.edge.course.interface.v1.CourseEdgeInterface/ListCourse"))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "GET", path, nil, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, err
}
