// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"github.com/go-kratos/kratos/v2"
	"github.com/go-kratos/kratos/v2/log"
	"microservice/app/course/service/internal/biz"
	"microservice/app/course/service/internal/conf"
	"microservice/app/course/service/internal/data"
	"microservice/app/course/service/internal/server"
	"microservice/app/course/service/internal/service"
)

// Injectors from wire.go:

// initApp init kratos application.
func initApp(confServer *conf.Server, confData *conf.Data, logger log.Logger) (*kratos.App, func(), error) {
	client := data.NewEntClient(confData, logger)
	dataData, cleanup, err := data.NewData(logger, client)
	if err != nil {
		return nil, nil, err
	}
	courseRepo := data.NewCourseRepo(dataData, logger)
	courseUseCase := biz.NewCourseUseCase(courseRepo, logger)
	courseService := service.NewCourseService(courseUseCase, logger)
	grpcServer := server.NewGRPCServer(confServer, courseService, logger)
	app := newApp(logger, grpcServer)
	return app, func() {
		cleanup()
	}, nil
}
