server:
  http:
    addr: 0.0.0.0:8000
    timeout: 5s
data:
  redis:
    addr: ${REDIS_ADDR}
    password: ""
    dial_timeout: 1s
    read_timeout: 0.4s
    write_timeout: 0.6s
external:
  message_service:
    addr: message-service
    port: 10900
  user_service:
    addr: localhost
    port: 10901


